src/libfsm/libfsm.syms: Add newline after `fsm_minimise_test_oracle`.
The lack of a newline after the `fsm_minimise_test_oracle` in the .syms
file used for `objcopy --keep-global-symbols` was causing the CI build
for gcc to fail:

> libfsm/tests/minimise/minimise_test_case_list.c:94: undefined reference to `fsm_minimise_test_oracle'
> collect2: error: ld returned 1 exit status

Mysteriously, this was only failing when using both gcc and
`-fsanitize=address`. Checked with gcc 7.5.0, 9.4.0, and 10.3.0.